#!/bin/bash
oldAttrbute=
newAttribute=
path=$(pwd)
help="$0 -o oldattribute -n newattribute (-p /path/to/metadata/directory/ | -f filename.xml). If f flag is not present, all files within the directory (specified with p flag or implicit . ) will be subject to attribute substitution."
if [ $# -gt "1" ]
then
	while getopts "o:n:p:f:h?" opt; do
		case "$opt" in
			o) oldAttribute=$OPTARG
			;;
			n) newAttribute=$OPTARG 
			;; 
			p) path=$OPTARG
			;;
			f) file=$OPTARG
			;;
			*) echo $help
			exit 1
			;;
		esac
	done
fi
cd $path
files=()
while IFS= read -r -d $'\0'; do
	files+=("$REPLY")
done < <(find . -name "*.xml" -print0)
#echo ${files[@]}
if [ ! -z ${file+x} ];then
	$(sed -i "s#$oldAttribute#$newAttribute#g" $file)	
else
	for f in ${files[@]};do
		$(sed -i "s#$oldAttribute#$newAttribute#g" $f)
	done
fi
exit 0
